import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MatButtonModule, MatCheckboxModule, MatSidenavModule, MatTooltipModule, MatExpansionModule, MatDatepickerModule, MatAutocompleteModule,
    MatInputModule, MatRadioModule, MatSelectModule, MatSlideToggleModule, MatMenuModule, MatToolbarModule, MatCardModule,
    MatButtonToggleModule, MatTabsModule, MatIconModule, MatProgressSpinnerModule, MatProgressBarModule, MatDialogModule, MatRippleModule,
    MatSnackBarModule, MatNativeDateModule, MatListModule, MatTableModule, MatPaginatorModule, MatPaginatorIntl, MatChipsModule, MatTree, MatTreeModule} from '@angular/material';

@NgModule({
  declarations: [],
  imports: [
    CommonModule,
    MatButtonModule,
    MatButtonToggleModule,
    MatCheckboxModule,
    MatSidenavModule,
    MatTooltipModule,
    MatExpansionModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatAutocompleteModule,
    MatInputModule,
    MatRadioModule,
    MatRippleModule,
    MatSelectModule,
    MatSlideToggleModule,
    MatMenuModule,
    MatToolbarModule,
    MatCardModule,
    MatTabsModule,
    MatIconModule,
    MatProgressSpinnerModule,
    MatProgressBarModule,
    MatDialogModule,
    MatSnackBarModule,
    MatTableModule,
    MatPaginatorModule,
    MatListModule,
    MatChipsModule,
    MatTreeModule,
  ],
  exports: [
      CommonModule,
      MatButtonModule,
      MatButtonToggleModule,
      MatCheckboxModule,
      MatSidenavModule,
      MatTooltipModule,
      MatExpansionModule,
      MatDatepickerModule,
      MatNativeDateModule,
      MatAutocompleteModule,
      MatInputModule,
      MatRippleModule,
      MatRadioModule,
      MatSelectModule,
      MatSlideToggleModule,
      MatMenuModule,
      MatToolbarModule,
      MatCardModule,
      MatTabsModule,
      MatIconModule,
      MatProgressSpinnerModule,
      MatProgressBarModule,
      MatDialogModule,
      MatSnackBarModule,
      MatTableModule,
      MatPaginatorModule,
      MatListModule,
      MatChipsModule,
      MatTreeModule
  ],
})
export class MaterialModule { }
